<?php
require_once 'BaseTest.php';
class AKServiceTest extends BaseTest
{
    private $service;
    private $signData;
    private $signTime;
    private $accessKey;

    public function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub
        $this->service = new \Monkey\Service\Impl\AKServiceImpl();
        $this->signData = ['chenbo' => 'test'];
        $this->signTime = strtotime('2018-05-16');
        $this->accessKey = 'access_key';
    }

    // tests
    public function testGenerate()
    {
        $data = $this->service->generate();
        $this->tester->seeInDatabase('access_secret_key', ['access_key' => $data['access_key']]);
    }

    public function testSignAndCheckSign(){
        $ak = $this->service->generate();
        $accessKey = $ak['access_key'];
        $originSign = $this->service->sign($accessKey, $this->signData, $this->signTime);
        $result = $this->service->checkSign($accessKey, $this->signData, $this->signTime, $originSign);
        $this->tester->assertTrue($result);
    }
}